### ISSUE TITLE
Desktop files

### ISSUE THREAD

**Issue by rapgro** [ncopa/xfce-bluetooth#2]
Please include both desktop files for better usability. This will autostart the agent on user login and insert the preferences dialog to general Xfce settings.
## /etc/xdg/autostart/xfce-bluetooth-agent.desktop

```
[Desktop Entry]
Version=1.0
Name=Xfce Bluetooth
Comment=The Xfce Bluetooth Agent
Exec=/usr/libexec/xfce-bluetooth-agent
Icon=bluetooth
Terminal=false
Type=Application
StartupNotify=false
OnlyShowIn=XFCE;
```
## /usr/share/applications/xfce-bluetooth.desktop

```
[Desktop Entry]
Version=1.0
Name=Bluetooth preferences
GenericName=Bluetooth preferences
Comment=Settings for the Xfce Bluetooth Manager
Exec=/usr/libexec/xfce-bluetooth
Icon=bluetooth
Terminal=false
Type=Application
Categories=XFCE;GTK;Settings;DesktopSettings;X-XFCE-SettingsDialog;X-XFCE-HardwareSettings;
OnlyShowIn=XFCE;
StartupNotify=true
X-XfcePluggable=true
X-XfceHelpComponent=xfce-bluetooth
X-XfceHelpPage=start
```

**Comment by ncopa** [comment]
Thanks. I'll add those.

I wonder if it woudl be an idea to move the both binaries to a place in $PATH. It probably does not make sense to have them in libexec dir.
